pipeline:
  name: Bidir-GitExp
  identifier: BidirGitExp
  projectIdentifier: Git_Sync
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: example
        identifier: example
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait
                  identifier: Wait
                  spec:
                    duration: 10s
        tags: {}
